// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bagian_blog: dynamic(() => import("./BagianBlog")),
  hero_image: dynamic(() => import("./HeroImage")),
  lokasi: dynamic(() => import("./Lokasi")),
  sejarah: dynamic(() => import("./Sejarah")),
  video: dynamic(() => import("./Video")),
};
