import type { Metadata } from "next";
import { Roboto_Flex } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";

const roboto = Roboto_Flex({ weight: "500", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dayak Basab",
  description: "Generated by Dayak Basab",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`light ${roboto.className}`}>
      <body className="bg-white">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
