import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PrelineScript from "./components/PrelineScripts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dayak Basab",
  description: "Generated by Dayak Basab",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} scroll-smooth`} >{children}</body>
      <PrelineScript />
    </html>
  );
}
