import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";

const oswald = Oswald({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dayak Basab",
  description: "Generated by Dayak Basab",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`light ${oswald.className}`} >
      <body >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
